package com.android.server.am;

import com.xiaopeng.util.DebugOption;
/* loaded from: classes.dex */
class ActivityManagerDebugConfig {
    static final boolean APPEND_CATEGORY_NAME = false;
    static final boolean DEBUG_ADD_REMOVE;
    static final boolean DEBUG_ALL = DebugOption.DEBUG_AM;
    static final boolean DEBUG_ALL_ACTIVITIES;
    static final boolean DEBUG_ANR = false;
    static final boolean DEBUG_APP;
    static final boolean DEBUG_BACKGROUND_CHECK;
    static final boolean DEBUG_BACKUP;
    static final boolean DEBUG_BROADCAST;
    static final boolean DEBUG_BROADCAST_BACKGROUND;
    static final boolean DEBUG_BROADCAST_LIGHT;
    static final boolean DEBUG_CLEANUP;
    static final boolean DEBUG_CONFIGURATION;
    static final boolean DEBUG_CONTAINERS;
    static final boolean DEBUG_FOCUS = false;
    static final boolean DEBUG_FOREGROUND_SERVICE;
    static final boolean DEBUG_IDLE;
    static final boolean DEBUG_IMMERSIVE;
    static final boolean DEBUG_LOCKTASK;
    static final boolean DEBUG_LRU;
    static final boolean DEBUG_METRICS;
    static final boolean DEBUG_MU;
    static final boolean DEBUG_NETWORK;
    static final boolean DEBUG_OOM_ADJ;
    static final boolean DEBUG_OOM_ADJ_REASON;
    static final boolean DEBUG_PAUSE;
    static final boolean DEBUG_PERMISSIONS_REVIEW;
    static final boolean DEBUG_POWER;
    static final boolean DEBUG_POWER_QUICK;
    static final boolean DEBUG_PROCESSES;
    static final boolean DEBUG_PROCESS_OBSERVERS;
    static final boolean DEBUG_PROVIDER;
    static final boolean DEBUG_PSS;
    static final boolean DEBUG_RECENTS;
    static final boolean DEBUG_RECENTS_TRIM_TASKS;
    static final boolean DEBUG_RELEASE;
    static final boolean DEBUG_RESULTS;
    static final boolean DEBUG_SAVED_STATE;
    static final boolean DEBUG_SERVICE;
    static final boolean DEBUG_SERVICE_EXECUTING;
    static final boolean DEBUG_STACK;
    static final boolean DEBUG_STATES;
    static final boolean DEBUG_SWITCH;
    static final boolean DEBUG_TASKS;
    static final boolean DEBUG_TRANSITION;
    static final boolean DEBUG_UID_OBSERVERS;
    static final boolean DEBUG_URI_PERMISSION;
    static final boolean DEBUG_USAGE_STATS;
    static final boolean DEBUG_USER_LEAVING;
    static final boolean DEBUG_VISIBILITY;
    static final boolean DEBUG_WHITELISTS;
    static final String POSTFIX_ADD_REMOVE = "";
    static final String POSTFIX_APP = "";
    static final String POSTFIX_BACKUP = "";
    static final String POSTFIX_BROADCAST = "";
    static final String POSTFIX_CLEANUP = "";
    static final String POSTFIX_CONFIGURATION = "";
    static final String POSTFIX_CONTAINERS = "";
    static final String POSTFIX_FOCUS = "";
    static final String POSTFIX_IDLE = "";
    static final String POSTFIX_IMMERSIVE = "";
    static final String POSTFIX_LOCKTASK = "";
    static final String POSTFIX_LRU = "";
    static final String POSTFIX_MU = "_MU";
    static final String POSTFIX_NETWORK = "_Network";
    static final String POSTFIX_OOM_ADJ = "";
    static final String POSTFIX_PAUSE = "";
    static final String POSTFIX_POWER = "";
    static final String POSTFIX_PROCESSES = "";
    static final String POSTFIX_PROCESS_OBSERVERS = "";
    static final String POSTFIX_PROVIDER = "";
    static final String POSTFIX_PSS = "";
    static final String POSTFIX_RECENTS = "";
    static final String POSTFIX_RELEASE = "";
    static final String POSTFIX_RESULTS = "";
    static final String POSTFIX_SAVED_STATE = "";
    static final String POSTFIX_SERVICE = "";
    static final String POSTFIX_SERVICE_EXECUTING = "";
    static final String POSTFIX_STACK = "";
    static final String POSTFIX_STATES = "";
    static final String POSTFIX_SWITCH = "";
    static final String POSTFIX_TASKS = "";
    static final String POSTFIX_TRANSITION = "";
    static final String POSTFIX_UID_OBSERVERS = "";
    static final String POSTFIX_URI_PERMISSION = "";
    static final String POSTFIX_USER_LEAVING = "";
    static final String POSTFIX_VISIBILITY = "";
    static final String TAG_AM = "ActivityManager";
    static final boolean TAG_WITH_CLASS_NAME = false;

    ActivityManagerDebugConfig() {
    }

    static {
        DEBUG_ALL_ACTIVITIES = DEBUG_ALL;
        DEBUG_ADD_REMOVE = DEBUG_ALL_ACTIVITIES;
        DEBUG_APP = DEBUG_ALL_ACTIVITIES;
        DEBUG_BACKGROUND_CHECK = DEBUG_ALL;
        DEBUG_BACKUP = DEBUG_ALL;
        DEBUG_BROADCAST = DEBUG_ALL || DebugOption.DEBUG_AM_BROADCAST;
        DEBUG_BROADCAST_BACKGROUND = DEBUG_BROADCAST;
        DEBUG_BROADCAST_LIGHT = DEBUG_BROADCAST;
        DEBUG_CLEANUP = DEBUG_ALL;
        DEBUG_CONFIGURATION = DEBUG_ALL;
        DEBUG_CONTAINERS = DEBUG_ALL_ACTIVITIES;
        DEBUG_IDLE = DEBUG_ALL_ACTIVITIES;
        DEBUG_IMMERSIVE = DEBUG_ALL;
        DEBUG_LOCKTASK = DEBUG_ALL;
        DEBUG_LRU = DEBUG_ALL;
        DEBUG_MU = DEBUG_ALL;
        DEBUG_NETWORK = DEBUG_ALL;
        DEBUG_OOM_ADJ = DEBUG_ALL;
        DEBUG_OOM_ADJ_REASON = DEBUG_ALL;
        DEBUG_PAUSE = DEBUG_ALL;
        DEBUG_POWER = DEBUG_ALL;
        DEBUG_POWER_QUICK = DEBUG_POWER;
        DEBUG_PROCESS_OBSERVERS = DEBUG_ALL;
        DEBUG_PROCESSES = DEBUG_ALL;
        DEBUG_PROVIDER = DEBUG_ALL;
        DEBUG_PSS = DEBUG_ALL;
        DEBUG_RECENTS = DEBUG_ALL;
        DEBUG_RECENTS_TRIM_TASKS = DEBUG_RECENTS;
        DEBUG_RELEASE = DEBUG_ALL_ACTIVITIES;
        DEBUG_RESULTS = DEBUG_ALL;
        DEBUG_SAVED_STATE = DEBUG_ALL_ACTIVITIES;
        DEBUG_SERVICE = DEBUG_ALL;
        DEBUG_FOREGROUND_SERVICE = DEBUG_ALL;
        DEBUG_SERVICE_EXECUTING = DEBUG_ALL;
        DEBUG_STACK = DEBUG_ALL;
        DEBUG_STATES = DEBUG_ALL_ACTIVITIES;
        DEBUG_SWITCH = DEBUG_ALL;
        DEBUG_TASKS = DEBUG_ALL;
        DEBUG_TRANSITION = DEBUG_ALL;
        DEBUG_UID_OBSERVERS = DEBUG_ALL;
        DEBUG_URI_PERMISSION = DEBUG_ALL;
        DEBUG_USER_LEAVING = DEBUG_ALL;
        DEBUG_VISIBILITY = DEBUG_ALL;
        DEBUG_USAGE_STATS = DEBUG_ALL;
        DEBUG_PERMISSIONS_REVIEW = DEBUG_ALL;
        DEBUG_WHITELISTS = DEBUG_ALL;
        DEBUG_METRICS = DEBUG_ALL;
    }
}
